### ISSUE TITLE
Retoques y traducciones infografías

### ISSUE THREAD

**Issue by EvaBelmonte** [civio/medicamentalia.org#1]
//Retoques. Son los dos de patentes:
- ¿Cómo funcionan las patentes?
	[] En 3 y 5, darle la vuelta y cambiar la tipo y la situación del número del artículo por el texto de abajo, que es mas importante.
	[] En la 6, no sé dónde están los países que salían, igual no está acabado y me estoy adelantando. + añadir este texto:  “Cada uno de ellos puede establecer, por ejemplo, extensiones a los periodos de monopolio o barreras más o menos altas para conseguir la concesión del derecho”

- Antimalárico:
	[] falta la flechica de Brasil a India

//Traducciones:

How do patents work?

In April 1994 the signing of the Marrakesh Agreement established the World Trade Organization (WTO).

Among the approved documents was the Agreement on Trade-Related Aspects of Intellectual Property Rights (TRIPS), whose section 5 regulates patents.

Patents apply not just to products but also to processes.
“Patents shall be available for any inventions, whether products or processes, in all fields of technology, provided that they are new, involve an inventive step and are capable of industrial application” 
Article 27.1

The agreement sets the framework for the compulsory licence in cases of national emergency or extreme urgency.
“Other Use Without Authorization of the Right Holder” shall also be permitted

The patent term is 20 years starting from the filing date, not from the day the patent is finally granted. 
“The term of protection available for a patent shall not end before the expiration of a period of twenty years counted from the filing date”
Article 33

Signatory countries.
The 161 country members of the WTO signed this agreement and adopted it in their national legislations.

A South-South antimalarial drug

An alliance beyond the market

The public laboratory Farmanginhos and DNDi (an organization dedicated to investigating treatments for neglected diseases) signs an agreement to develop an antimalarial drug. The Brazilian pharmaceutical industry, universities and research institutions sign too. 

ASMQ is born

Farmanginhos (located in Rio de Janeiro) produces ASMQ, an artesunate-mefloquine fixed-dose combination used to treat more than half of the malaria cases in Brazil. It was registered in 2008.

Across Latin America

The new drug, developed in the public system and outside market dynamics, reaches other Latin American countries such as Bolivia and Venezuela through donations and agreements.

To Southeast Asia

The technology to produce the drug is transferred from a public laboratory in Brazil to a private laboratory in India (Cipla), a South-South public-private partnership so that it can be produced there in order to reach other countries in Southeast Asia.

And soon to Africa

Permission to enable production lines has been requested to the WHO so the drug can also be distributed in African countries.

The routes of counterfeit medicines 

Boatloads of counterfeit drugs are shipped from Mumbai, India.

The drugs get to West Africa through the Gulf of Guinea, and are smuggled through less-guarded countries such as Togo.

Once on land, the cargo is transported by road to more developed countries such as Ghana or Nigeria.

**Comment by rauldiazpoblete** [comment]
Este issue pertenece al repositorio civio/medicamentalia-theme: 
https://github.com/civio/medicamentalia-theme/issues/5
https://github.com/civio/medicamentalia-theme/issues/6
